name: "ğŸ•¹ï¸ Issue Triage Labels"

on:
  issues:
    types: [opened]

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: "Remove 'Status: Needs Triage' if issue already has an assignee"
        if: ${{ github.event.issue.assignee != null }}
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: "Status: Needs Triage"

      - name: "Add 'Status: Needs Triage' if issue has no assignee"
        if: ${{ github.event.issue.assignee == null }}
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: "Status: Needs Triage"
